#! /usr/bin/env sh

set -eu

# These environment variables are sometimes needed by the running daemons
export USER="{{ tiles_user }}"
export HOME="/home/{{ tiles_user }}"

export MAPNIK_FONT_PATH="$HOME/.fonts"
cd $HOME
exec node_modules/tessera/bin/tessera.js -p {{ tiles_tessera_port }} -b 127.0.0.1 tmstyle://./mapbox-studio-osm-bright.tm2
