#!/bin/sh
/sbin/ip link set dev $INTERFACE up
/sbin/ip addr add dev $INTERFACE {{ icvpn_addr_v4 }}/{{icvpn_subnet_v4}} broadcast {{ icvpn_subnet_brdcast }} scope link
/sbin/ip -6 addr add dev $INTERFACE {{ icvpn_addr_v6 }}/{{icvpn_subnet_v6}} preferred_lft 0

# ip rules
/sbin/ip rule add lookup {{ icvpn_table }} priority 10042
/sbin/ip -6 rule add lookup {{ icvpn_table }} priority 10042
