#! /usr/bin/env bash

set -eu

# These environment variables are sometimes needed by the running daemons
export USER={{ downloads_user }}
export HOME=/home/{{ downloads_user }}

# Include the user-specific profile, it's actually called .profile on debian.
. $HOME/.profile

# Now let's go!
exec /usr/bin/rsync --no-detach --daemon --config $HOME/.config/etc/rsyncd.conf 2>&1
