#! /usr/bin/env bash

# These environment variables are sometimes needed by the running daemons
export USER={{ etherpad_user }}
export HOME=/home/{{ etherpad_user }}

# Include the user-specific profile, it's actually called .profile on debian.
. /etc/profile.d/node_version.sh

# Now let's go!
cd "$HOME/.opt/etherpad"
./bin/installDeps.sh
exec ./bin/run.sh 2>&1
