#! /usr/bin/env bash

# These environment variables are sometimes needed by the running daemons
export USER=ffhb-wiki
export HOME=/home/ffhb-wiki

export GOLLUM_ENV_PATH="$HOME/.var/gollum-envs/ff-bremen"
export GOLLUM_BASE_PATH='/'
export GOLLUM_BIND_ADDR='127.0.0.1'
export GOLLUM_BIND_PORT='63112'

cd $HOME/.opt/gollum
# Now let's go!
exec bundle exec bin/gollum --port "${GOLLUM_BIND_PORT}" --host "${GOLLUM_BIND_ADDR}" --adapter rugged --live-preview --css --h1-title "${GOLLUM_ENV_PATH}" 2>&1
