#! /usr/bin/env bash

# These environment variables are sometimes needed by the running daemons
export PATH=/sbin:/usr/sbin:/bin:/usr/bin
export USER={{ tasks_user }}
export HOME=/home/{{ tasks_user }}

. "$HOME/.local/bin/php_env.sh"

INSTALL_ROOT="/var/www/{{ tasks_user }}/opt/phabricator"
PHD_TMP_DIR="$HOME/.var/tmp/phabricator"

for PHD_NEEDED_DIR in log pid; do
  if [ ! -d "${PHD_TMP_DIR}/${PHD_NEEDED_DIR}" ]; then
    mkdir -p "${PHD_TMP_DIR}/${PHD_NEEDED_DIR}"
  fi
done

DAEMON_FILE="$HOME/.var/tmp/phabricator-daemon-file"

cat > "$DAEMON_FILE" <<EOF
{
    "daemonize": false,
    "daemons": [
        {
            "class": "PhabricatorRepositoryPullLocalDaemon",
            "label": "PhabricatorRepositoryPullLocalDaemon"
        },
        {
            "class": "PhabricatorTriggerDaemon",
            "label": "PhabricatorTriggerDaemon"
        },
        {
            "class": "PhabricatorTaskmasterDaemon",
            "label": "PhabricatorTaskmasterDaemon"
        }
    ],
    "log": "${PHD_TMP_DIR}/log/daemons.log",
    "piddir": "${PHD_TMP_DIR}/pid"
}
EOF

# Now let's go!
exec "$INSTALL_ROOT/phabricator/scripts/daemon/phd-daemon" < "$DAEMON_FILE" 2>&1
