#! /usr/bin/env bash

set -eu

# These environment variables are sometimes needed by the running daemons
export USER={{ wiki_user }}
export HOME=/home/{{ wiki_user }}

export GOLLUM_ENV_PATH="$HOME/.var/gollum-envs/ff-bremen"
export GOLLUM_BIND_ADDR='127.0.0.1'
export GOLLUM_BIND_PORT='{{ wiki_gollum_port }}'

cd $HOME/.opt/gollum
# Now let's go!
exec bundle exec ~/.opt/gollum/bin/gollum --port "${GOLLUM_BIND_PORT}" --host "${GOLLUM_BIND_ADDR}" --adapter rugged --live-preview --css --h1-title "${GOLLUM_ENV_PATH}" 2>&1
