#! /usr/bin/env bash
# 2014, Moritz Kaspar Rudert (mortzu) <mr@planetcyborg.de>.
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this list of
#   conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this list
#   of conditions and the following disclaimer in the documentation and/or other materials
#   provided with the distribution.
#
# * The names of its contributors may not be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# * Feel free to send Club Mate to support the work.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i ERR_CODE=$STATE_OK
declare -i EXPIRE_DATE=0

if ! which lsb_release >/dev/null; then
  ERR_CODE=$STATE_UNKNOWN
  ERR_MSG='lsb_release not found'
else
  DISTRIBUTION="$(lsb_release -is)"
  RELEASE="$(lsb_release -cs)"

  case "$DISTRIBUTION" in
    Debian)
      case "$RELEASE" in
        bo)
          ERR_CODE=$STATE_CRITICAL
          ERR_MSG="EOL of $RELEASE is absolutely expired."
        ;;
        rex)
          ERR_CODE=$STATE_CRITICAL
          ERR_MSG="EOL of $RELEASE is absolutely expired."
        ;;
        buzz)
          ERR_CODE=$STATE_CRITICAL
          ERR_MSG="EOL of $RELEASE is absolutely expired."
        ;;
        hamm)
          EXPIRE_DATE=19990309
        ;;
        slink)
          EXPIRE_DATE=20001030
        ;;
        potato)
          EXPIRE_DATE=20030630
        ;;
        woody)
          EXPIRE_DATE=20060630
        ;;
        sarge)
          EXPIRE_DATE=20080330
        ;;
        etch)
          EXPIRE_DATE=20100215
        ;;
        lenny)
          EXPIRE_DATE=20120201
        ;;
        squeeze)
          EXPIRE_DATE=20140505
        ;;
        wheezy)
          EXPIRE_DATE=20180531
        ;;
        jessie)
          EXPIRE_DATE=20200630
        ;;
        stretch)
          EXPIRE_DATE=20220630
        ;;
        buster)
          EXPIRE_DATE=20240630
        ;;
        sid)
          ERR_CODE=$STATE_OK
        ;;
        *)
          ERR_CODE=$STATE_UNKNOWN
          ERR_MSG="Release ($RELEASE) unknown in script."
        ;;
      esac
    ;;
    Ubuntu)
      case "$RELEASE" in
        warty)
          EXPIRE_DATE=20060430
        ;;
        hoary)
          EXPIRE_DATE=20061031
        ;;
        breezy)
          EXPIRE_DATE=20070413
        ;;
        dapper)
          EXPIRE_DATE=20110601
        ;;
        edgy)
          EXPIRE_DATE=20080425
        ;;
        feisty)
          EXPIRE_DATE=20081019
        ;;
        gutsy)
          EXPIRE_DATE=20090418
        ;;
        hardy)
          EXPIRE_DATE=20130401
        ;;
        intrepid)
          EXPIRE_DATE=20100430
        ;;
        jaunty)
          EXPIRE_DATE=20101023
        ;;
        karmic)
          EXPIRE_DATE=20110430
        ;;
        lucid)
          EXPIRE_DATE=20150401
        ;;
        maverick)
          EXPIRE_DATE=20120401
        ;;
        natty)
          EXPIRE_DATE=20121001
        ;;
        oneiric)
          EXPIRE_DATE=20130401
        ;;
        precise)
          EXPIRE_DATE=20170401
        ;;
        trusty)
          EXPIRE_DATE=20190401
        ;;
        xenial)
          EXPIRE_DATE=20210401
        ;;
        *)
          ERR_CODE=$STATE_UNKNOWN
          ERR_MSG="Release ($RELEASE) unknown in script."
        ;;
      esac
    ;;
    *)
      case $(lsb_release -sd) in
        '"Arch Linux"')
          ERR_CODE=$STATE_OK
          ERR_MSG='ArchLinux is a rolling release distribution. So no release updates are required.'
        ;;
        *)
          ERR_CODE=$STATE_UNKNOWN
          ERR_MSG="Distribution ($DISTRIBUTION) unknown in script."
        ;;
      esac
    ;;
  esac
fi

if [ $ERR_CODE -eq $STATE_OK -a -z "$ERR_MSG" ]; then
  if [ $EXPIRE_DATE -gt 0 ]; then
    if [ $EXPIRE_DATE -lt $(date +%Y%m%d) ]; then
      ERR_CODE=$STATE_CRITICAL
      ERR_MSG="EOL of $RELEASE has expired ($(date -d $EXPIRE_DATE +%d.%m.%Y))."
    else
      ERR_MSG="EOL of $RELEASE has not expired ($(date -d $EXPIRE_DATE +%d.%m.%Y))."
    fi
  else
    ERR_MSG="EOL of $RELEASE has not expired."
  fi
fi

if [ $ERR_CODE -eq $STATE_OK ]; then
  echo "OK: ${ERR_MSG}"
else
  echo "CRITICAL: ${ERR_MSG}"
fi

exit $ERR_CODE
