#! /usr/bin/env sh

# derived from /etc/network/if-pre-up.d/bridge
# depends on /lib/bridge-utils/bridge-utils.sh from bridge-utils

if ! modprobe -q batman-adv; then
    exit 0
fi

. /lib/bridge-utils/bridge-utils.sh

case "$IF_BATADV_PORTS" in
    "")
        exit 0
    ;;
    none)
        exit 0
    ;;
    *)
        INTERFACES="$IF_BATADV_PORTS"
    ;;
esac

# taken from openWRT:
# https://git.openwrt.org/?p=feed/routing.git;a=blob;f=batman-adv/files/lib/netifd/proto/batadv.sh;h=edc14f4cbd5485ede408e897fada8eae6f8f09d3;hb=ecb7132f014275a9fa0509e790257f0a66802a1d#l72
# maybe following is possible after create:
# batctl meshif "$IFACE" routing_algo "${IF_BATADV_ROUTING_ALGO:-BATMAN_IV}"
batctl routing_algo "${IF_BATADV_ROUTING_ALGO:-BATMAN_IV}"

if ! batctl meshif "$IFACE" interface >/dev/null 2>&1; then
    batctl meshif "$IFACE" interface create
fi

all_interfaces= &&
unset all_interfaces &&
bridge_parse_ports $INTERFACES | while read i; do
    for port in $i; do
        # We attach and configure each port of the bridge
        if [ "$MODE" = "start" ] && ! batctl meshif "$IFACE" interface | grep --quiet "^${port}:"; then
            if [ -x /etc/network/if-pre-up.d/vlan ]; then
                env IFACE=$port /etc/network/if-pre-up.d/vlan
            fi

            if [ "$IF_BATADV_HW" ]; then
                ip link set down dev "$port"
                ip link set dev "$port" address "$IF_BATADV_HW"
            fi

            if [ -f /proc/sys/net/ipv6/conf/$port/disable_ipv6 ]; then
                echo 1 > /proc/sys/net/ipv6/conf/$port/disable_ipv6
            fi

            batctl meshif "$IFACE" interface add -M "$port"
            ip link set up dev "$port"
        # We detach each port of the bridge
        elif [ "$MODE" = "stop" ] && batctl meshif "$IFACE" interface | grep --quiet "^${port}:";  then
            ip link set down dev "$port"
            batctl meshif "$IFACE" interface del -M "$port"

            if [ -x /etc/network/if-post-down.d/vlan ]; then
                env IFACE=$port /etc/network/if-post-down.d/vlan
            fi

           if [ -f /proc/sys/net/ipv6/conf/$port/disable_ipv6 ]; then
               echo 0 > /proc/sys/net/ipv6/conf/$port/disable_ipv6
           fi
        fi
    done
done

if [ "$IF_BATADV_HW" ]; then
    ip link set dev "$IFACE" address "$IF_BATADV_HW"
fi

# We finish setting up the bridge
if [ "$MODE" = "start" ] ; then
    if [ "$IF_BATADV_HOP_PENALTY" ]; then
        batctl meshif "$IFACE" hop_penalty "$IF_BATADV_HOP_PENALTY"
    fi

    if [ "$IF_BATADV_GW_MODE" ]; then
        batctl meshif "$IFACE" gw_mode "$IF_BATADV_GW_MODE"

        if [ "$IF_BATADV_GW_BANDWIDTH" ]; then
            batctl meshif "$IFACE" gw_mode "$IF_BATADV_GW_MODE" "$IF_BATADV_GW_BANDWIDTH"
        fi
    fi

    # We activate the bridge
    ip link set up dev "$IFACE"
fi
