#! /usr/bin/env bash

PATH="/home/{{ monitoring_user }}/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/{{ monitoring_user }}/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/{{ monitoring_user }}/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/{{ monitoring_user }}/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/{{ monitoring_user }}/perl5"; export PERL_MM_OPT;

/home/{{ monitoring_user }}/.opt/sendxmpp/sendxmpp $@
